// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vAPI.Models;

#nullable disable

namespace vAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241115104814_BookingDetailsModelUpdated")]
    partial class BookingDetailsModelUpdated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("vAPI.Models.BookingDetailsModel", b =>
                {
                    b.Property<string>("BookingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("D1HospitalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("D1SlotNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("D2HospitalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("D2SlotNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Dose1Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Dose2Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserVaccinationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BookingId");

                    b.ToTable("BookingDetails");
                });

            modelBuilder.Entity("vAPI.Models.UserDetailsModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UserBirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserGender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserUid")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("vAPI.Models.UserVaccineDetailsModel", b =>
                {
                    b.Property<string>("UserVaccinationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserVaccinationStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserVaccinationId");

                    b.ToTable("UserVaccineDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
